services:
  my-ebank-discovery-service:
    build: ./discovery-service
    container_name: my-ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 5
  my-ebank-config-service:
    build: ./config-service
    container_name: my-ebank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 5
    environment:
      - DISCOVERY_SERVICE_URL=http://my-ebank-discovery-service:8761/eureka
    depends_on:
      my-ebank-discovery-service:
        condition: service_healthy
  my-ebank-customer-service:
    build: ./customer-service
    container_name: my-ebank-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 5
    environment:
      - DISCOVERY_SERVICE_URL=http://my-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://my-ebank-config-service:9999
    depends_on:
      my-ebank-config-service:
        condition: service_healthy
  my-ebank-account-service:
    build: ./account-service
    container_name:   my-ebank-account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://my-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://my-ebank-config-service:9999
    depends_on:
      my-ebank-customer-service:
        condition: service_healthy
  my-ebank-gateway-service:
    build: ./gateway-service
    container_name:   my-ebank-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://my-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://my-ebank-config-service:9999
    depends_on:
      my-ebank-config-service:
        condition: service_healthy
  front-end-angular:
    build: ./angular-front-end
    container_name: front-end-angular
    ports:
      - '80:80'
    expose:
      - '80'
